name: deploy my Lambda function
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python on the runner
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          cd functions
          python -m pip install --upgrade pip
          if [-f requirements.txt]; then pip install -r requirements.txt -t .; fi
      - name : Zip the function
        run: |
          cd functions
          zip -r ../{{ github.sha }}.zip .
      - name: Archive the artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip